FROM oven/bun:latest AS deps
WORKDIR /app

COPY package.json bun.lock ./
COPY bun.lock ./
RUN bun install

FROM oven/bun:latest AS dev
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY . .

EXPOSE 5173

CMD ["bun", "run", "dev", "--host"]
