FROM oven/bun:latest AS dev
WORKDIR /app

# Copia de package.json y bun.lockb
COPY frontend/package.json frontend/bun.lockb ./

# Instalación de dependencias
RUN bun install

# Monta el código y exponemos el puerto de Vite
COPY frontend/. .

EXPOSE 5173

# Lanza el dev server de Vite con Bun
CMD ["bun", "run", "dev", "--", "--host", "0.0.0.0"]