FROM node:lts-alpine AS builder
WORKDIR /app
COPY frontend/package.json frontend/package-lock.json* ./
RUN npm ci
COPY frontend/. .
RUN npm run build

FROM nginx:stable-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY deployment/frontend/nginx/conf.d/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 5173
