apiVersion: apps/v1
kind: Deployment
metadata:
  name: network-debug
  namespace: kartingrm
  labels:
    app: network-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network-debug
  template:
    metadata:
      labels:
        app: network-debug
    spec:
      containers:
      - name: netshoot
        image: nicolaka/netshoot:latest
        command: ["sleep", "infinity"]
        securityContext:
          runAsUser: 0
        resources:
          limits:
            cpu:    "200m"
            memory: "256Mi"
