pipeline {
    agent any
    stages {
        stage('Stage 1') {
            steps {
                sh '''#!/bin/bash
                                    ls
                            '''
            }
        }
    }
}