FROM maven:3.9-eclipse-temurin-17
WORKDIR /app
COPY backend/pom.xml .

RUN mvn dependency:go-offline -B


EXPOSE 35729
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-Duser.timezone=UTC -Xshare:off"]