FROM openjdk:17-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y maven git vim curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./backend/pom.xml .

RUN mvn dependency:go-offline

EXPOSE 8080
EXPOSE 35729  # Puerto para LiveReload

ENV SPRING_PROFILES_ACTIVE=dev

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]