services:
  backend:
    build:
      context: ../../
      dockerfile: deployment/backend/Dockerfile.dev
    ports:
      - "8080:8080"
      - "35729:35729"
      - "8000:8000"
    volumes:
      - ../../backend/src:/app/src
      - ../../backend/pom.xml:/app/pom.xml
      - maven-repo:/root/.m2
    env_file:
      - ./.env
    environment:
      - SPRING_DEVTOOLS_REMOTE_SECRET=mysecretkey
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network


  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - app-network


  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    env_file:
      - ./.env
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network


volumes:
  maven-repo:

networks:
  app-network:
    driver: bridge