FROM maven:3.9.9-amazoncorretto-17 AS build

WORKDIR /app

COPY ../../backend/pom.xml .
COPY ../../backend/src ./src

RUN mvn dependency:go-offline -B

RUN mvn package -DskipTests

FROM amazoncorretto:17-alpine

WORKDIR /app

ENV SPRING_PROFILES_ACTIVE=prod
ENV SERVER_PORT=8080
ENV TZ="America/Santiago"

COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]