version: '3'

services:
  backend:
    build:
      context: ../../
      dockerfile: deployment/backend/Dockerfile.dev
    ports:
      - "8080:8080"
      - "35729:35729"  # Puerto para LiveReload
    volumes:
      - ../../backend/src:/app/src
      - ../../backend/pom.xml:/app/pom.xml
      - maven-repo:/root/.m2
    env_file:
      - ./.env.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    env_file:
      - ./.env.dev
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    env_file:
      - ./.env.dev
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  maven-repo: