apiVersion: apps/v1
kind: Deployment
metadata:
  name: kartingrm-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: kartingrm-frontend
  template:
    metadata:
      labels:
        app: kartingrm-frontend
    spec:
      containers:
      - name: frontend
        image: {{ $.Values.artifactRegistry.location }}-docker.pkg.dev/{{ $.Values.artifactRegistry.projectId }}/{{ $.Values.artifactRegistry.repository }}/{{ $.Values.frontend.image }}:{{ $.Values.imageTag }}
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: {{ .Values.frontend.apiUrl }}
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: kartingrm-frontend
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: kartingrm-frontend
