{{- range .Values.microservices }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: {{ $.Values.artifactRegistry.location }}-docker.pkg.dev/{{ $.Values.artifactRegistry.projectId }}/{{ $.Values.artifactRegistry.repository }}/{{ .name }}:{{ $.Values.imageTag }}
          ports:
            - containerPort: 8081
              name: management
          env:
            - name: SERVER_PORT
              value: "0"
            - name: MANAGEMENT_SERVER_PORT
              value: "8081"
            - name: SPRING_APPLICATION_NAME
              value: {{ .name }}
            - name: SPRING_PROFILES_ACTIVE
              value: "{{ $.Values.springProfiles }},microservices"

            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: {{ $.Values.eurekaUrl }}
            - name: SPRING_CLOUD_CONFIG_URI
              value: {{ $.Values.configServerUrl }}
            - name: SPRING_CONFIG_IMPORT
              value: "configserver:{{ $.Values.configServerUrl }}"

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}-db-secret
                  key: url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}-db-secret
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}-db-secret
                  key: password

            - name: SPRING_MAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: host
            - name: SPRING_MAIL_PORT
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: port
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: username
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: email-secret
                  key: password

            # Timezone
            - name: TZ
              value: America/Santiago

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: management
            initialDelaySeconds: 45
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: management
            initialDelaySeconds: 90
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8081
      name: http
  selector:
    app: {{ .name }}
{{- end }}