apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-server-files
  namespace: {{ .Values.namespace }}
data:
  application.yml: |
    spring:
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
      
      datasource:
        driver-class-name: org.postgresql.Driver
      
      mail:
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
    
    eureka:
      instance:
        prefer-ip-address: true
      client:
        registry-fetch-interval-seconds: 10
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info
      endpoint:
        health:
          show-details: always
