apiVersion: v1
kind: Secret
metadata:
  name: email-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  host: {{ .Values.email.host | b64enc }}
  port: {{ .Values.email.port | b64enc }}
  username: {{ .Values.email.username | b64enc }}
  password: {{ .Values.email.password | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  host: {{ .Values.database.host | b64enc }}
  port: {{ .Values.database.port | b64enc }}
  password: {{ .Values.database.password | b64enc }}

---
{{- range .Values.microservices }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-db-secret
  namespace: {{ $.Values.namespace }}
type: Opaque
data:
  url: {{ printf "jdbc:postgresql://%s:%s/%s?sslmode=disable" $.Values.database.host $.Values.database.port .dbName | b64enc }}
  username: {{ .dbUser | b64enc }}
  password: {{ $.Values.database.password | b64enc }}
---
{{- end }}
